CREATE TABLE IF NOT EXISTS users (
  id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  varchar(255) NOT NULL,
  email varchar(512) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS item_requests (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id      bigint REFERENCES users (id) ON DELETE CASCADE,
  description   varchar(512) NOT NULL,
  created_date  timestamp
);

CREATE TABLE IF NOT EXISTS items (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id      bigint REFERENCES users (id) ON DELETE CASCADE,
  name          varchar(255) NOT NULL,
  description   varchar(512) NOT NULL,
  is_available  boolean,
  request_id    bigint REFERENCES item_requests (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date timestamp NOT NULL,
  end_date   timestamp NOT NULL,
  booker_id  bigint REFERENCES users (id) ON DELETE CASCADE,
  item_id    bigint REFERENCES items (id) ON DELETE CASCADE,
  status     varchar(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text      varchar(512) NOT NULL,
  item_id   bigint REFERENCES items (id) ON DELETE CASCADE,
  author_id bigint REFERENCES users (id) ON DELETE CASCADE,
  created   timestamp NOT NULL
);
